"""FakeFeedz: built-in page scraper that generates synthetic RSS feeds for feedless pages.

Two scraping modes:
  - link_list: extract links from a page; each new link becomes a feed entry.
  - change_detect: hash-compare page content; a new entry is created on each change.

Feeds are stored as file:// RSS 2.0 XML files under DATA_DIR/scraped-feeds/. The reader
library natively supports file:// URIs, so these feeds are treated exactly like remote
feeds — read/unread state, starring, tags, and automation rules all work out of the box.
"""
from __future__ import annotations

import hashlib
import logging
import sqlite3
import uuid
from datetime import datetime, timezone
from email.utils import format_datetime as _format_rfc2822
from pathlib import Path
from urllib.parse import urljoin

import httpx
from bs4 import BeautifulSoup

from services import assert_safe_feed_id, url_guard

LOGGER = logging.getLogger(__name__)

_scraped_feeds_dir: Path | None = None

_FETCH_HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; Lectio/1.0)"}
_MAX_CONTENT_BYTES = 8_000
_MAX_ENTRIES_PER_FEED = 50


def init(data_dir: Path) -> None:
    global _scraped_feeds_dir
    _scraped_feeds_dir = data_dir / "scraped-feeds"
    _scraped_feeds_dir.mkdir(parents=True, exist_ok=True)


def _dir() -> Path:
    assert _scraped_feeds_dir is not None, "scraper_service.init() not called"
    return _scraped_feeds_dir


def feed_file_url(feed_id: str) -> str:
    return f"file://{_dir() / (feed_id + '.xml')}"


def scraped_feed_id_from_url(file_url: str) -> str | None:
    """Extract the feed UUID from a file:// feed URL, or None if not a scraped feed.

    Dir-aware so it never matches a file URL owned by another synthetic-feed
    source (e.g. DeviantArt) that also lives under DATA_DIR.
    """
    if not file_url.startswith("file://"):
        return None
    p = Path(file_url[len("file://"):])
    if p.parent != _dir():
        return None
    return p.stem or None


# ---------------------------------------------------------------------------
# HTTP + HTML helpers
# ---------------------------------------------------------------------------

def _fetch_html(url: str) -> str:
    # follow_redirects=False so url_guard.safe_get validates every hop (SSRF).
    with httpx.Client(timeout=20, follow_redirects=False, headers=_FETCH_HEADERS) as client:
        resp = url_guard.safe_get(client, url)
        resp.raise_for_status()
        return resp.text


def _page_title(html: str, fallback: str) -> str:
    try:
        soup = BeautifulSoup(html, "html.parser")
        if soup.title and soup.title.string:
            return soup.title.string.strip()[:200]
    except Exception:
        pass
    return fallback


# ---------------------------------------------------------------------------
# RSS file generation
# ---------------------------------------------------------------------------

def _entry_to_item_xml(entry: dict, source_url: str) -> str:
    try:
        dt = datetime.fromisoformat(str(entry["published_at"]))
        pub_date = f"<pubDate>{_format_rfc2822(dt)}</pubDate>"
    except Exception:
        pub_date = ""
    link = str(entry.get("entry_url") or source_url)
    content = str(entry.get("content") or "")[:_MAX_CONTENT_BYTES]
    title = str(entry.get("title") or link)
    return (
        "    <item>\n"
        f"      <title><![CDATA[{title}]]></title>\n"
        f"      <link>{link}</link>\n"
        f"      <guid isPermaLink=\"false\">{entry['id']}</guid>\n"
        f"      {pub_date}\n"
        f"      <description><![CDATA[{content}]]></description>\n"
        "    </item>"
    )


def _generate_rss_xml(feed_title: str, source_url: str, entries: list[dict]) -> str:
    items_xml = "\n".join(_entry_to_item_xml(e, source_url) for e in entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0">\n'
        "  <channel>\n"
        f"    <title><![CDATA[{feed_title}]]></title>\n"
        f"    <link>{source_url}</link>\n"
        "    <description>FakeFeedz — generated by Lectio</description>\n"
        f"{items_xml}\n"
        "  </channel>\n"
        "</rss>\n"
    )


def _write_feed_file(conn: sqlite3.Connection, feed_id: str) -> None:
    assert_safe_feed_id(feed_id)
    row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    if not row:
        return
    entries = [
        dict(r)
        for r in conn.execute(
            "SELECT * FROM scraped_entries"
            " WHERE scraped_feed_id = ? AND NOT hidden"
            " ORDER BY published_at DESC LIMIT ?",
            (feed_id, _MAX_ENTRIES_PER_FEED),
        ).fetchall()
    ]
    xml = _generate_rss_xml(str(row["feed_title"]), str(row["source_url"]), entries)
    (_dir() / f"{feed_id}.xml").write_text(xml, encoding="utf-8")


def _write_empty_feed_file(feed_id: str, feed_title: str, source_url: str) -> None:
    assert_safe_feed_id(feed_id)
    xml = _generate_rss_xml(feed_title, source_url, [])
    (_dir() / f"{feed_id}.xml").write_text(xml, encoding="utf-8")


# ---------------------------------------------------------------------------
# Link extraction + selector suggestions (shared by scraping and preview)
# ---------------------------------------------------------------------------

def _resolve_link_anchors(soup: BeautifulSoup, selector: str) -> list:
    """Resolve a selector to the anchor elements it targets.

    A selector copied from "inspect element" often targets a container (e.g. a
    <li> or <div>) rather than the <a> inside it. Use a selected element directly
    if it's an <a> with an href, otherwise pull the descendant anchors — preserving
    document order and dropping duplicates. No selector => every anchor on the page.
    """
    selected = soup.select(selector) if selector else soup.find_all("a")
    anchors: list = []
    seen: set[int] = set()
    for el in selected:
        candidates = [el] if (el.name == "a" and el.get("href")) else el.find_all("a")
        for anchor in candidates:
            if not anchor.get("href") or id(anchor) in seen:
                continue
            seen.add(id(anchor))
            anchors.append(anchor)
    return anchors


def _anchor_to_item(anchor, source_url: str) -> dict | None:
    """Turn an <a> into a preview/entry dict {title, url}, or None if unusable."""
    href = str(anchor.get("href") or "").strip()
    if not href or href.startswith("#") or href.startswith("javascript:"):
        return None
    abs_url = urljoin(source_url, href)
    title = anchor.get_text(" ", strip=True)[:500] or abs_url
    return {"title": title, "url": abs_url}


def extract_link_items(html: str, source_url: str, selector: str) -> list[dict]:
    """Items a link-list selector would produce: [{title, url}], de-duped by url."""
    soup = BeautifulSoup(html, "html.parser")
    items: list[dict] = []
    seen_urls: set[str] = set()
    for anchor in _resolve_link_anchors(soup, str(selector or "").strip()):
        item = _anchor_to_item(anchor, source_url)
        if not item or item["url"] in seen_urls:
            continue
        seen_urls.add(item["url"])
        items.append(item)
    return items


def _css_ident(value: str) -> str:
    """A CSS class/id token safe to drop into a selector, or '' if unusable
    (dynamic/hashed tokens with odd characters are skipped)."""
    import re as _re
    value = value.strip()
    if value and _re.fullmatch(r"[A-Za-z_-][A-Za-z0-9_-]*", value):
        return value
    return ""


def _candidate_selector_for_anchor(anchor) -> str | None:
    """Build a simple, stable selector describing an anchor within its list group.

    Prefers the anchor's own class, then its parent container's tag+class (e.g.
    ``li.item a``), so anchors sharing a repeating structure collapse to one key.
    Returns None when nothing stable can be derived."""
    a_class = next((c for c in (anchor.get("class") or []) if _css_ident(c)), "")
    if a_class:
        return f"a.{_css_ident(a_class)}"
    parent = anchor.parent
    if parent is not None and getattr(parent, "name", None):
        p_class = next((c for c in (parent.get("class") or []) if _css_ident(c)), "")
        if p_class:
            return f"{parent.name}.{_css_ident(p_class)} a"
        grandparent = parent.parent
        gp_name = getattr(grandparent, "name", None)
        if gp_name and gp_name not in ("[document]", "html", "body"):
            return f"{gp_name} > {parent.name} a"
    return None


def suggest_selectors(html: str, source_url: str, limit: int = 6) -> list[dict]:
    """Suggest link-list selectors by grouping anchors that share a structure.

    Returns ranked ``[{selector, count, samples}]`` — most links first — so the UI
    can offer one-click chips instead of hand-written CSS."""
    soup = BeautifulSoup(html, "html.parser")
    groups: dict[str, list[dict]] = {}
    for anchor in soup.find_all("a"):
        item = _anchor_to_item(anchor, source_url)
        if not item:
            continue
        selector = _candidate_selector_for_anchor(anchor)
        if not selector:
            continue
        groups.setdefault(selector, []).append(item)

    suggestions: list[dict] = []
    for selector, items in groups.items():
        # Verify the derived selector actually resolves (skip if BS4 rejects it),
        # and use the resolved de-duped count so the chip matches the live preview.
        try:
            resolved = extract_link_items(html, source_url, selector)
        except Exception:
            continue
        if len(resolved) < 2:
            continue  # a single link isn't a "list" worth suggesting
        suggestions.append({
            "selector": selector,
            "count": len(resolved),
            "samples": [it["title"] for it in resolved[:3]],
        })

    def _rank(s: dict) -> tuple:
        # A generic tag-only descendant selector like "div > div a" usually catches
        # site nav/login chrome. Demote only those: a class-based selector OR a
        # list-item ("li a") selector points at real content. Everything else is
        # then ranked by how many links it gathers.
        sel = s["selector"]
        has_class = "." in sel
        is_list = "li a" in sel
        is_generic_chrome = not has_class and not is_list
        return (not is_generic_chrome, s["count"])

    suggestions.sort(key=_rank, reverse=True)
    return suggestions[:limit]


# ---------------------------------------------------------------------------
# Scraping modes
# ---------------------------------------------------------------------------

def _scrape_change_detect(conn: sqlite3.Connection, feed: dict) -> bool:
    """Hash-compare page (or selected element) content. Creates an entry when content changes."""
    try:
        html = _fetch_html(str(feed["source_url"]))
    except Exception as exc:
        LOGGER.warning("[scraper] fetch failed for %s: %s", feed["source_url"], exc)
        return False

    selector = str(feed.get("selector") or "").strip()
    if selector:
        try:
            soup = BeautifulSoup(html, "html.parser")
            content = "".join(str(el) for el in soup.select(selector))
        except Exception:
            content = html
    else:
        content = html

    new_hash = hashlib.sha256(content.encode()).hexdigest()
    now = datetime.now(timezone.utc).isoformat()

    if new_hash == feed.get("last_content_hash"):
        conn.execute("UPDATE scraped_feeds SET last_scraped_at = ? WHERE id = ?", (now, feed["id"]))
        return False

    page_title = _page_title(html, str(feed["feed_title"]))
    entry_id = str(uuid.uuid4())
    conn.execute(
        "INSERT INTO scraped_entries (id, scraped_feed_id, entry_url, title, content, published_at, hidden)"
        " VALUES (?, ?, ?, ?, ?, ?, 0)",
        (entry_id, feed["id"], feed["source_url"], f"{page_title} — updated", content[:_MAX_CONTENT_BYTES], now),
    )
    conn.execute(
        "UPDATE scraped_feeds SET last_content_hash = ?, last_scraped_at = ? WHERE id = ?",
        (new_hash, now, feed["id"]),
    )
    return True


def _scrape_link_list(conn: sqlite3.Connection, feed: dict, initial: bool = False) -> bool:
    """Extract links; add new ones as (optionally hidden) entries. Returns True if new visible entries added."""
    try:
        html = _fetch_html(str(feed["source_url"]))
    except Exception as exc:
        LOGGER.warning("[scraper] fetch failed for %s: %s", feed["source_url"], exc)
        return False

    selector = str(feed.get("selector") or "").strip()
    soup = BeautifulSoup(html, "html.parser")
    link_elements = _resolve_link_anchors(soup, selector)

    existing_urls: set[str] = {
        str(r["entry_url"])
        for r in conn.execute(
            "SELECT entry_url FROM scraped_entries WHERE scraped_feed_id = ?", (feed["id"],)
        ).fetchall()
    }

    now = datetime.now(timezone.utc).isoformat()
    new_visible = 0

    for a in link_elements:
        item = _anchor_to_item(a, str(feed["source_url"]))
        if not item:
            continue
        abs_url = item["url"]
        if abs_url in existing_urls:
            continue
        existing_urls.add(abs_url)
        title = item["title"]
        entry_id = str(uuid.uuid4())
        hidden = 1 if initial else 0
        conn.execute(
            "INSERT OR IGNORE INTO scraped_entries"
            " (id, scraped_feed_id, entry_url, title, content, published_at, hidden)"
            " VALUES (?, ?, ?, ?, ?, ?, ?)",
            (entry_id, feed["id"], abs_url, title, "", now, hidden),
        )
        if not initial:
            new_visible += 1

    conn.execute("UPDATE scraped_feeds SET last_scraped_at = ? WHERE id = ?", (now, feed["id"]))
    return new_visible > 0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def preview_page_feed(source_url: str, mode: str, selector: str | None) -> dict:
    """Preview what a page feed would produce, without creating anything.

    Returns ``{title, mode, items, suggestions, content_preview}``:
    - ``items``: link-list entries [{title, url}] the selector would yield;
    - ``suggestions``: ranked candidate selectors for link_list mode;
    - ``content_preview``: text excerpt of the watched region for change_detect.
    Raises on fetch failure so the route can surface the error."""
    html = _fetch_html(source_url)
    title = _page_title(html, source_url)
    sel = (selector or "").strip()
    out: dict = {"title": title, "mode": mode, "items": [], "suggestions": [], "content_preview": ""}
    if mode == "link_list":
        out["suggestions"] = suggest_selectors(html, source_url)
        if sel:
            out["items"] = extract_link_items(html, source_url, sel)[:50]
    else:
        try:
            soup = BeautifulSoup(html, "html.parser")
            content = "".join(str(el) for el in soup.select(sel)) if sel else html
        except Exception:
            content = html
        text = BeautifulSoup(content, "html.parser").get_text(" ", strip=True)
        out["content_preview"] = text[:600]
    return out


def create_scraped_feed(
    conn: sqlite3.Connection,
    reader,
    source_url: str,
    mode: str,
    selector: str | None,
    feed_title: str | None,
    backfill: bool = False,
) -> tuple[str, str]:
    """Create a scraped feed, do initial scrape, register with reader. Returns (feed_id, file_url).

    When ``backfill`` is set (link_list only), pre-existing links are surfaced as
    visible entries rather than seeded hidden.

    The caller is responsible for adding the feed to a folder in folder_feeds.
    """
    assert mode in ("change_detect", "link_list"), f"unknown scraping mode: {mode!r}"

    feed_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    if not feed_title:
        try:
            html = _fetch_html(source_url)
            feed_title = _page_title(html, source_url)
        except Exception:
            feed_title = source_url

    conn.execute(
        "INSERT INTO scraped_feeds (id, source_url, mode, selector, feed_title, created_at)"
        " VALUES (?, ?, ?, ?, ?, ?)",
        (feed_id, source_url, mode, selector or None, feed_title, now),
    )

    # Write empty XML first so reader can open the file immediately.
    _write_empty_feed_file(feed_id, feed_title, source_url)

    feed_row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    feed = dict(feed_row)

    if mode == "link_list":
        # Seed existing links as hidden so they aren't surfaced as new entries,
        # unless backfill was requested — then surface them as visible entries.
        _scrape_link_list(conn, feed, initial=not backfill)
    else:
        # Capture initial hash and create a first entry so the feed isn't empty on
        # first view — subsequent page changes will generate additional entries.
        try:
            html = _fetch_html(source_url)
            sel = (selector or "").strip()
            if sel:
                try:
                    soup = BeautifulSoup(html, "html.parser")
                    content = "".join(str(el) for el in soup.select(sel))
                except Exception:
                    content = html
            else:
                content = html
            initial_hash = hashlib.sha256(content.encode()).hexdigest()
            conn.execute(
                "UPDATE scraped_feeds SET last_content_hash = ?, last_scraped_at = ? WHERE id = ?",
                (initial_hash, now, feed_id),
            )
            conn.execute(
                "INSERT INTO scraped_entries (id, scraped_feed_id, title, entry_url, content, published_at)"
                " VALUES (?, ?, ?, ?, ?, ?)",
                (str(uuid.uuid4()), feed_id, feed_title, source_url, content[:_MAX_CONTENT_BYTES], now),
            )
        except Exception as exc:
            LOGGER.warning("[scraper] initial setup failed for %s: %s", source_url, exc)

    _write_feed_file(conn, feed_id)

    file_url = feed_file_url(feed_id)
    reader.add_feed(file_url, exist_ok=True)
    try:
        reader.update_feed(file_url)
    except Exception:
        pass
    return feed_id, file_url


def delete_scraped_feed(conn: sqlite3.Connection, reader, feed_id: str) -> None:
    """Remove a scraped feed: clean up DB rows, delete XML file, unsubscribe from reader."""
    assert_safe_feed_id(feed_id)
    file_url = feed_file_url(feed_id)
    conn.execute("DELETE FROM scraped_entries WHERE scraped_feed_id = ?", (feed_id,))
    conn.execute("DELETE FROM scraped_feeds WHERE id = ?", (feed_id,))
    try:
        (_dir() / f"{feed_id}.xml").unlink(missing_ok=True)
    except Exception:
        pass
    try:
        reader.delete_feed(file_url, missing_ok=True)
    except Exception:
        pass


def refresh_scraped_feed_by_id(conn: sqlite3.Connection, feed_id: str) -> bool:
    """Refresh a single scraped feed and rewrite its XML file. Returns True if new visible entries."""
    row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    if not row:
        return False
    feed = dict(row)
    if feed["mode"] == "change_detect":
        changed = _scrape_change_detect(conn, feed)
    else:
        changed = _scrape_link_list(conn, feed)
    _write_feed_file(conn, feed_id)
    return changed


def refresh_all_scraped_feeds(conn: sqlite3.Connection) -> None:
    """Refresh every scraped feed and rewrite its XML file."""
    try:
        rows = conn.execute("SELECT id FROM scraped_feeds").fetchall()
    except Exception:
        return  # table may not exist in test environments
    for row in rows:
        try:
            refresh_scraped_feed_by_id(conn, str(row["id"]))
        except Exception:
            LOGGER.exception("[scraper] error refreshing feed %s", row["id"])


def get_all_scraped_feeds(conn: sqlite3.Connection) -> list[dict]:
    """Return metadata for all scraped feeds."""
    return [dict(r) for r in conn.execute("SELECT * FROM scraped_feeds ORDER BY feed_title").fetchall()]
