"""FakeFeedz: built-in page scraper that generates synthetic RSS feeds for feedless pages.

Two scraping modes:
  - link_list: extract links from a page; each new link becomes a feed entry.
  - change_detect: hash-compare page content; a new entry is created on each change.

Feeds are stored as file:// RSS 2.0 XML files under DATA_DIR/scraped-feeds/. The reader
library natively supports file:// URIs, so these feeds are treated exactly like remote
feeds — read/unread state, starring, tags, and automation rules all work out of the box.
"""
from __future__ import annotations

import hashlib
import logging
import sqlite3
import uuid
from datetime import datetime, timezone
from email.utils import format_datetime as _format_rfc2822
from pathlib import Path
from urllib.parse import urljoin

import httpx
from bs4 import BeautifulSoup

from services import url_guard

LOGGER = logging.getLogger(__name__)

_scraped_feeds_dir: Path | None = None

_FETCH_HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; Lectio/1.0)"}
_MAX_CONTENT_BYTES = 8_000
_MAX_ENTRIES_PER_FEED = 50


def init(data_dir: Path) -> None:
    global _scraped_feeds_dir
    _scraped_feeds_dir = data_dir / "scraped-feeds"
    _scraped_feeds_dir.mkdir(parents=True, exist_ok=True)


def _dir() -> Path:
    assert _scraped_feeds_dir is not None, "scraper_service.init() not called"
    return _scraped_feeds_dir


def feed_file_url(feed_id: str) -> str:
    return f"file://{_dir() / (feed_id + '.xml')}"


def scraped_feed_id_from_url(file_url: str) -> str | None:
    """Extract the feed UUID from a file:// feed URL, or None if not a scraped feed.

    Dir-aware so it never matches a file URL owned by another synthetic-feed
    source (e.g. DeviantArt) that also lives under DATA_DIR.
    """
    if not file_url.startswith("file://"):
        return None
    p = Path(file_url[len("file://"):])
    if p.parent != _dir():
        return None
    return p.stem or None


# ---------------------------------------------------------------------------
# HTTP + HTML helpers
# ---------------------------------------------------------------------------

def _fetch_html(url: str) -> str:
    # follow_redirects=False so url_guard.safe_get validates every hop (SSRF).
    with httpx.Client(timeout=20, follow_redirects=False, headers=_FETCH_HEADERS) as client:
        resp = url_guard.safe_get(client, url)
        resp.raise_for_status()
        return resp.text


def _page_title(html: str, fallback: str) -> str:
    try:
        soup = BeautifulSoup(html, "html.parser")
        if soup.title and soup.title.string:
            return soup.title.string.strip()[:200]
    except Exception:
        pass
    return fallback


# ---------------------------------------------------------------------------
# RSS file generation
# ---------------------------------------------------------------------------

def _entry_to_item_xml(entry: dict, source_url: str) -> str:
    try:
        dt = datetime.fromisoformat(str(entry["published_at"]))
        pub_date = f"<pubDate>{_format_rfc2822(dt)}</pubDate>"
    except Exception:
        pub_date = ""
    link = str(entry.get("entry_url") or source_url)
    content = str(entry.get("content") or "")[:_MAX_CONTENT_BYTES]
    title = str(entry.get("title") or link)
    return (
        "    <item>\n"
        f"      <title><![CDATA[{title}]]></title>\n"
        f"      <link>{link}</link>\n"
        f"      <guid isPermaLink=\"false\">{entry['id']}</guid>\n"
        f"      {pub_date}\n"
        f"      <description><![CDATA[{content}]]></description>\n"
        "    </item>"
    )


def _generate_rss_xml(feed_title: str, source_url: str, entries: list[dict]) -> str:
    items_xml = "\n".join(_entry_to_item_xml(e, source_url) for e in entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0">\n'
        "  <channel>\n"
        f"    <title><![CDATA[{feed_title}]]></title>\n"
        f"    <link>{source_url}</link>\n"
        "    <description>FakeFeedz — generated by Lectio</description>\n"
        f"{items_xml}\n"
        "  </channel>\n"
        "</rss>\n"
    )


def _write_feed_file(conn: sqlite3.Connection, feed_id: str) -> None:
    row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    if not row:
        return
    entries = [
        dict(r)
        for r in conn.execute(
            "SELECT * FROM scraped_entries"
            " WHERE scraped_feed_id = ? AND NOT hidden"
            " ORDER BY published_at DESC LIMIT ?",
            (feed_id, _MAX_ENTRIES_PER_FEED),
        ).fetchall()
    ]
    xml = _generate_rss_xml(str(row["feed_title"]), str(row["source_url"]), entries)
    (_dir() / f"{feed_id}.xml").write_text(xml, encoding="utf-8")


def _write_empty_feed_file(feed_id: str, feed_title: str, source_url: str) -> None:
    xml = _generate_rss_xml(feed_title, source_url, [])
    (_dir() / f"{feed_id}.xml").write_text(xml, encoding="utf-8")


# ---------------------------------------------------------------------------
# Scraping modes
# ---------------------------------------------------------------------------

def _scrape_change_detect(conn: sqlite3.Connection, feed: dict) -> bool:
    """Hash-compare page (or selected element) content. Creates an entry when content changes."""
    try:
        html = _fetch_html(str(feed["source_url"]))
    except Exception as exc:
        LOGGER.warning("[scraper] fetch failed for %s: %s", feed["source_url"], exc)
        return False

    selector = str(feed.get("selector") or "").strip()
    if selector:
        try:
            soup = BeautifulSoup(html, "html.parser")
            content = "".join(str(el) for el in soup.select(selector))
        except Exception:
            content = html
    else:
        content = html

    new_hash = hashlib.sha256(content.encode()).hexdigest()
    now = datetime.now(timezone.utc).isoformat()

    if new_hash == feed.get("last_content_hash"):
        conn.execute("UPDATE scraped_feeds SET last_scraped_at = ? WHERE id = ?", (now, feed["id"]))
        return False

    page_title = _page_title(html, str(feed["feed_title"]))
    entry_id = str(uuid.uuid4())
    conn.execute(
        "INSERT INTO scraped_entries (id, scraped_feed_id, entry_url, title, content, published_at, hidden)"
        " VALUES (?, ?, ?, ?, ?, ?, 0)",
        (entry_id, feed["id"], feed["source_url"], f"{page_title} — updated", content[:_MAX_CONTENT_BYTES], now),
    )
    conn.execute(
        "UPDATE scraped_feeds SET last_content_hash = ?, last_scraped_at = ? WHERE id = ?",
        (new_hash, now, feed["id"]),
    )
    return True


def _scrape_link_list(conn: sqlite3.Connection, feed: dict, initial: bool = False) -> bool:
    """Extract links; add new ones as (optionally hidden) entries. Returns True if new visible entries added."""
    try:
        html = _fetch_html(str(feed["source_url"]))
    except Exception as exc:
        LOGGER.warning("[scraper] fetch failed for %s: %s", feed["source_url"], exc)
        return False

    selector = str(feed.get("selector") or "").strip()
    soup = BeautifulSoup(html, "html.parser")
    link_elements = soup.select(selector) if selector else soup.find_all("a")

    existing_urls: set[str] = {
        str(r["entry_url"])
        for r in conn.execute(
            "SELECT entry_url FROM scraped_entries WHERE scraped_feed_id = ?", (feed["id"],)
        ).fetchall()
    }

    now = datetime.now(timezone.utc).isoformat()
    new_visible = 0

    for a in link_elements:
        href = str(a.get("href") or "").strip()
        if not href or href.startswith("#") or href.startswith("javascript:"):
            continue
        abs_url = urljoin(str(feed["source_url"]), href)
        if abs_url in existing_urls:
            continue
        existing_urls.add(abs_url)
        title = a.get_text(strip=True)[:500] or abs_url
        entry_id = str(uuid.uuid4())
        hidden = 1 if initial else 0
        conn.execute(
            "INSERT OR IGNORE INTO scraped_entries"
            " (id, scraped_feed_id, entry_url, title, content, published_at, hidden)"
            " VALUES (?, ?, ?, ?, ?, ?, ?)",
            (entry_id, feed["id"], abs_url, title, "", now, hidden),
        )
        if not initial:
            new_visible += 1

    conn.execute("UPDATE scraped_feeds SET last_scraped_at = ? WHERE id = ?", (now, feed["id"]))
    return new_visible > 0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def create_scraped_feed(
    conn: sqlite3.Connection,
    reader,
    source_url: str,
    mode: str,
    selector: str | None,
    feed_title: str | None,
) -> tuple[str, str]:
    """Create a scraped feed, do initial scrape, register with reader. Returns (feed_id, file_url).

    The caller is responsible for adding the feed to a folder in folder_feeds.
    """
    assert mode in ("change_detect", "link_list"), f"unknown scraping mode: {mode!r}"

    feed_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    if not feed_title:
        try:
            html = _fetch_html(source_url)
            feed_title = _page_title(html, source_url)
        except Exception:
            feed_title = source_url

    conn.execute(
        "INSERT INTO scraped_feeds (id, source_url, mode, selector, feed_title, created_at)"
        " VALUES (?, ?, ?, ?, ?, ?)",
        (feed_id, source_url, mode, selector or None, feed_title, now),
    )

    # Write empty XML first so reader can open the file immediately.
    _write_empty_feed_file(feed_id, feed_title, source_url)

    feed_row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    feed = dict(feed_row)

    if mode == "link_list":
        # Seed existing links as hidden so they aren't surfaced as new entries.
        _scrape_link_list(conn, feed, initial=True)
    else:
        # Capture initial hash and create a first entry so the feed isn't empty on
        # first view — subsequent page changes will generate additional entries.
        try:
            html = _fetch_html(source_url)
            sel = (selector or "").strip()
            if sel:
                try:
                    soup = BeautifulSoup(html, "html.parser")
                    content = "".join(str(el) for el in soup.select(sel))
                except Exception:
                    content = html
            else:
                content = html
            initial_hash = hashlib.sha256(content.encode()).hexdigest()
            conn.execute(
                "UPDATE scraped_feeds SET last_content_hash = ?, last_scraped_at = ? WHERE id = ?",
                (initial_hash, now, feed_id),
            )
            conn.execute(
                "INSERT INTO scraped_entries (id, scraped_feed_id, title, entry_url, content, published_at)"
                " VALUES (?, ?, ?, ?, ?, ?)",
                (str(uuid.uuid4()), feed_id, feed_title, source_url, content[:_MAX_CONTENT_BYTES], now),
            )
        except Exception as exc:
            LOGGER.warning("[scraper] initial setup failed for %s: %s", source_url, exc)

    _write_feed_file(conn, feed_id)

    file_url = feed_file_url(feed_id)
    reader.add_feed(file_url, exist_ok=True)
    try:
        reader.update_feed(file_url)
    except Exception:
        pass
    return feed_id, file_url


def delete_scraped_feed(conn: sqlite3.Connection, reader, feed_id: str) -> None:
    """Remove a scraped feed: clean up DB rows, delete XML file, unsubscribe from reader."""
    file_url = feed_file_url(feed_id)
    conn.execute("DELETE FROM scraped_entries WHERE scraped_feed_id = ?", (feed_id,))
    conn.execute("DELETE FROM scraped_feeds WHERE id = ?", (feed_id,))
    try:
        (_dir() / f"{feed_id}.xml").unlink(missing_ok=True)
    except Exception:
        pass
    try:
        reader.delete_feed(file_url, missing_ok=True)
    except Exception:
        pass


def refresh_scraped_feed_by_id(conn: sqlite3.Connection, feed_id: str) -> bool:
    """Refresh a single scraped feed and rewrite its XML file. Returns True if new visible entries."""
    row = conn.execute("SELECT * FROM scraped_feeds WHERE id = ?", (feed_id,)).fetchone()
    if not row:
        return False
    feed = dict(row)
    if feed["mode"] == "change_detect":
        changed = _scrape_change_detect(conn, feed)
    else:
        changed = _scrape_link_list(conn, feed)
    _write_feed_file(conn, feed_id)
    return changed


def refresh_all_scraped_feeds(conn: sqlite3.Connection) -> None:
    """Refresh every scraped feed and rewrite its XML file."""
    try:
        rows = conn.execute("SELECT id FROM scraped_feeds").fetchall()
    except Exception:
        return  # table may not exist in test environments
    for row in rows:
        try:
            refresh_scraped_feed_by_id(conn, str(row["id"]))
        except Exception:
            LOGGER.exception("[scraper] error refreshing feed %s", row["id"])


def get_all_scraped_feeds(conn: sqlite3.Connection) -> list[dict]:
    """Return metadata for all scraped feeds."""
    return [dict(r) for r in conn.execute("SELECT * FROM scraped_feeds ORDER BY feed_title").fetchall()]
